# Generated by Django 5.1.6 on 2025-03-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('product_id', models.CharField(max_length=250)),
                ('order_id', models.CharField(max_length=250)),
            ],
        ),
    ]
