# Generated by Django 5.1.6 on 2025-03-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='order_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='product_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
