# Generated by Django 5.1.6 on 2025-03-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_remove_product_quantity_cartitem_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
